export const popolDb = [
  {
    id: " vips ",
    title: "VIPS",
    project: "RENEWAL PROJECT",
    team: "TEAM PROJECT (주성찬, 양수영)",
    day: "2022/08/08",
    bg: "img/pp/ppvipsbg.png",
    img1: "img/pp/ppvipsimg1.png",
    img2: "img/pp/ppvipsimg2.png",
    img3: "img/pp/ppvipsimg3.png",
  },
  {
    id: "JMOVIES",
    title: "J MOVIES",
    project: "CREATE PROJECT",
    team: "PERSONAL PROJECT (주성찬)",
    day: "2022/07/20",
    bg: "img/pp/ppjmoviesbg.png",
    img1: "img/pp/ppjmoviesimg1.png",
    img2: "img/pp/ppjmoviesimg2.png",
    img3: "img/pp/ppjmoviesimg3.png",
  },
  {
    id: "seoul ",
    title: "서울식물원",
    project: "RENEWAL PROJECT",
    team: "TEAM PROJECT (주성찬, 박희정, 강정현)",
    day: "2022/06/14",
    bg: "img/pp/ppseoulbg.png",
    img1: "img/pp/ppseoulimg1.png",
    img2: "img/pp/ppseoulimg2.png",
    img3: "img/pp/ppseoulimg3.png",
  },
  {
    id: " joo ",
    title: "Joo-Movies",
    project: "CLONE PROJECT",
    team: "PERSONAL PROJECT (주성찬)",
    day: "2022/06/25",
    bg: "img/pp/ppjoobg.png",
    img1: "img/pp/ppjooimg1.png",
    img2: "img/pp/ppjooimg2.png",
    img3: "img/pp/ppjooimg3.png",
  },
];
