export const popolDb = [
  {
    id: " vips ",
    title: "VIPS",
    project: "RENEWAL PROJECT",
    team: "TEAM PROJECT (주성찬, 양수영)",
    day: "2022/08/08",
    bg: "img/PP/ppvipsbg.png",
    img1: "img/PP/ppvipsimg1.png",
    img2: "img/PP/ppvipsimg2.png",
    img3: "img/PP/ppvipsimg3.png",
  },
  {
    id: "JMOVIES",
    title: "J MOVIES",
    project: "CREATE PROJECT",
    team: "PERSONAL PROJECT (주성찬)",
    day: "2022/07/20",
    bg: "img/PP/ppjmoviesbg.png",
    img1: "img/PP/ppjmoviesimg1.png",
    img2: "img/PP/ppjmoviesimg2.png",
    img3: "img/PP/ppjmoviesimg3.png",
  },
  {
    id: "seoul ",
    title: "서울식물원",
    project: "RENEWAL PROJECT",
    team: "TEAM PROJECT (주성찬, 박희정, 강정현)",
    day: "2022/06/14",
    bg: "img/PP/ppseoulbg.png",
    img1: "img/PP/ppseoulimg1.png",
    img2: "img/PP/ppseoulimg2.png",
    img3: "img/PP/ppseoulimg3.png",
  },
  {
    id: " joo ",
    title: "Joo-Movies",
    project: "CLONE PROJECT",
    team: "PERSONAL PROJECT (주성찬)",
    day: "2022/06/25",
    bg: "img/PP/ppjoobg.png",
    img1: "img/PP/ppjooimg1.png",
    img2: "img/PP/ppjooimg2.png",
    img3: "img/PP/ppjooimg3.png",
  },
];
